# Site settings
title: 
header-img: img/home-bg.png
email: neimeier.1@osu.edu
copyright_name: AubreyNeimeier
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AubreyNeimeier
learn_profile: AubreyNeimeier
email_username: neimeier.1@osu.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
